---
framework: jest
preRun:
     command:
        - yarn install
        - yarn workspace demo-app test-build-scripts
preMerge:
  pattern:
    - "./**/__tests__/**/*-test.js"
    - "/demo-app/src/example/tests/Example.react-test.js"
postMerge:
  pattern: 
    - "./**/__tests__/**/*-test.js"
    - "/demo-app/src/example/tests/Example.react-test.js"
postRun:
     command:
        - yarn --version
version: 1.0
